### PR TITLE
Feature/footer concept

### PR DESCRIPTION
**Pull request by TraceLD**
As discussed on Discord I've created this layout. Let me know what you think @capnkenny

### CODE REVIEW

**Comment by capnkenny** [comment]
This looks pretty good!

However, this now makes me question the header colour hahahah 😅 Do you have any suggestions on what we could change that to? Or do you think we'd want to leave that be?

**Comment by TraceLD** [comment]
> This looks pretty good!
> 
> However, this now makes me question the header colour hahahah 😅 Do you have any suggestions on what we could change that to? Or do you think we'd want to leave that be?

I mean it's subjective, I like it personally 🤷‍♂️

**Comment by capnkenny** [comment]
> 
> 
> > This looks pretty good!
> > However, this now makes me question the header colour hahahah 😅 Do you have any suggestions on what we could change that to? Or do you think we'd want to leave that be?
> 
> I mean it's subjective, I like it personally 🤷‍♂️

Lol that's very true. I'll give this another look tonight then and merge if I find no issues with it.

**Review by capnkenny — APPROVED** [review]
LGTM!

**Pull request merged**
